### ISSUE TITLE
GetTypeFromProgID devuelve nulo

### ISSUE THREAD

**Issue by pablopapes** [reingart/pyafipws#10]
en el ejemplo de .net C# tengo un problema al momento de crear el objeto interface Web Service de Factura Electrónica de Mercado Interno

  dynamic WSFEv1 = Activator.CreateInstance(Type.GetTypeFromProgID("WSFEv1"));
El valor no puede ser nulo.
Nombre del parámetro: type

ya que Type.GetTypeFromProgID("WSFEv1") devuelve nulo

Instale Pyafipws desde el ultimo realease para windows en github. los certificados con afip y demas ( la autenticacion con el webservice la realiza perfecta )

**Comment by reingart** [comment]
No creo que sea un tema técnico, aparentemente es un problema de instalación (los instaladores publicados en GitHub pueden no estar actualizados). Descargar desde:

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#Descargas

Contestado en el foro:

https://groups.google.com/d/msg/pyafipws/QGQXHRhQ27M/UPpbQH928xMJ
