### ISSUE TITLE
¿Es necesario seguir utilizando py3k?

### ISSUE THREAD

**Issue by nimarosa** [reingart/pyafipws#102]
Estaba re-factorizando la localización Argentina que mantenemos para Odoo, y me surgio la duda ya que se viene arrastrando en la localización el uso de la branch de pyafipws@py3k. 

Entiendo que los desarrolladores iniciales (paso por muchas manos la localización), utilizaban esa branch porque asi se indica en este thread de la wiki: https://github.com/reingart/pyafipws/wiki/Factura-Electronica-Python-3

Mi consulta en particular, sobre todo para @reingart es: ¿Es necesario seguir usando esa branch para python 3.X? ¿O tranquilamente podriamos estar consumiendo la branch main?

Si bien todo funciona ok con la py3k, entiendo que en la main existen nuevos métodos que se han ido agregando que son útiles justamente para el refactoreo que estoy haciendo. Pero me surge la duda ya que históricamente se uso py3k siempre en la localización. ¿Hay algún motivo o diferencia entre branches que estoy ignorando? 

Desde ya muchas gracias por la aclaracion.

**Comment by nimarosa** [comment]
Por si alguien más se lo pregunta. No, no es necesario. Se puede usar la rama main y anda mucho mejor y soluciona errores viejos. Cerrando...

**Comment by reingart** [comment]
Gracias @nimarosa ! 
Si, la rama main es la más actualizada, tiene los tests automatizados e  instaladores.
Tengo pendiente el PR #101  que es compatible con Python 3.11 por si lo necesitan.
En algún momento voy a implementar que se publique en PyPI el paquete.
PD: Disculpas recién veo el comment, cualquier duda que tengan con la rama main avisennos

**Comment by nimarosa** [comment]
> Gracias @nimarosa ! 
> 
> Si, la rama main es la más actualizada, tiene los tests automatizados e  instaladores.
> 
> Tengo pendiente el PR #101  que es compatible con Python 3.11 por si lo necesitan.
> 
> En algún momento voy a implementar que se publique en PyPI el paquete.
> 
> PD: Disculpas recién veo el comment, cualquier duda que tengan con la rama main avisennos

@reingart por ahora funciona estupendo. Las localizaciones de Odoo hace rato que por defecto vienen indicando que debe usarse la rama py3k así que cuando me puse a refactorearla probé la main y va incluso te diría mas rápido que py3k. 

Incluso ahora estoy trabajando en integrar los batch de AFIP en odoo, ya que actualmente se autoriza una factura a la vez, pero siempre existió la problemática de enviar grandes números de facturas a autorizar y vi que pyafipws lo soporta con los métodos InciarFacturaX, etc asi que seguro lo esté implementando en estos días. 

Todo este refactoreo que estoy armando se va a publicar como localización oficial de Argentina en los repositorios de OCA (OCA/l10n-argentina) por si queres verlo cuando esté subido o te sirve. Yo soy el PSC mantenedor de ese repo y otros de OCA asi que la idea es ya pasar a la rama main en la loc. oficial e implementar todos los métodos nuevos que existen en "main" y no en py3k. 

Lo de que el paquete se publique en PyPI si sería buenísimo, ya que asi se puede instalar fácilmente declarándolo como dependencia en el manifest de los módulos de Odoo. Si necesitas ayuda con eso avísame y te puedo dar una mano, ya que es muy útil poder instalar pyafipws directo desde pip. 

Por otro lado, gran proyecto y te felicito por seguir manteniéndolo, es de mucha utilidad para todo Argentina, y la verdad funciona bárbaro. 

Un saludo y estoy a disposición si necesitas algún tipo de ayuda, abrazo!

**Comment by reingart** [comment]
Hola @nimarosa ! gracias por los comentarios!

Todavía no tuve tiempo de avanzar con el tema de PyPI, pero si tienen algún workflow para GitHub sería buenísimo para agregarlo (ya estamos usando el de python package para buildear y probar los unit tests).
Desde ya toda ayuda es bienvenida.

BTW, ya arrancó el GSoC, son becas ($1500 a $3000 USD, 3 a 6 meses) para nuevos colaboradores de software libre (estudiantes o programadores que estén iniciando). 
Se podría participar con alguna propuesta para este proyecto o relacionado (ej esta integración de PyPI para la localización Argentina podría ser ideal).

Si conocen algún interesado avisnenos , pueden ver más información en la página de Python Argentina: https://www.python.org.ar/noticias/34/

y en el foro hay mas detalles: https://groups.google.com/g/pyafipws/c/tXSGJomOlvk/m/2JCHFx1cAgAJ

Instrucciones en la wiki: https://wiki.python.org.ar/GSoC/2023/#pyafipws
