### ISSUE TITLE
COT - Incompatibilidad en python 3

### ISSUE THREAD

**Issue by gbertolani** [reingart/pyafipws#113]
Hola, como estas?

Estaba probando lo del cot, pero hay una incompatibilidad en python 3 al intentar verificar si un objeto es instancia de la clase **file** 

El error es el siguiente

  File "/usr/local/lib/python3.8/site-packages/pyafipws/cot.py", line 110, in PresentarRemito
    response = self.client(
  File "/usr/local/lib/python3.8/site-packages/pyafipws/utils.py", line 589, in __call__
    boundary, body = self.multipart_encode(vars)
  File "/usr/local/lib/python3.8/site-packages/pyafipws/utils.py", line 551, in multipart_encode
    if not isinstance(value, file):
NameError: name 'file' is not defined

Encontré este  [Issue#111](https://github.com/reingart/pyafipws/issues/111) cerrado pero no aclara como se soluciono.

**Comment by reingart** [comment]
Hola @gbertolani este tema esta corregido en el branch de PyAr:

https://github.com/PyAr/pyafipws/blob/main/utils.py#L549

En cuanto pueda voy a mergear esos cambios en mi rama personal, recomendaría usar esa rama para python3 ya que recibe mas actualizaciones de la comunidad.

Gracias por el reporte y buen año!
