### ISSUE TITLE
PNG con canal Alfa

### ISSUE THREAD

**Issue by lbonomo** [reingart/pyafipws#15]
Cuando desde un equipo con Linux (Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux) genero una factura con un logo en formato PNG con canal Alfa, dicho PDF no se puede visualizar en equipos con Windows con Acrobat Reader (ultimas versiones)

Se genera correctamente al eliminar el canal alfa del PNG.

**Comment by reingart** [comment]
Gracias por reportarlo
¿podrías adjuntar ejemplos con imágenes de prueba para intentar reproducirlo?

**Comment by lbonomo** [comment]
Si utilizo esta imagen, Acrobat Reader no muestra el documento.

![logo](https://cloud.githubusercontent.com/assets/1223367/8722540/07c7aeb0-2b9c-11e5-90ee-9fc6e6df9889.png)
