### ISSUE TITLE
SSLTimeout

### ISSUE THREAD

**Issue by jpmermoz** [reingart/pyafipws#20]
Buen día,

Durante ciertos momentos del día obtengo errores de SSLTimeout al intentar facturar. No ocurre todo el momento. Durante los últimos 2 dias pasa más que nada durante el mediodía.

Quería saber si alguno tuvo un problema similar, y si existe alguna solución.

Muchas gracias!

**Comment by andresmaiden** [comment]
Hola, a mi me está pasando bastante seguido. Y me pasa otra cosa más, en
alguno de los casos que me da SSL Timeout, el AFIP emite la factura y le
asigna CAE, pero no obtengo la respuesta de dicho CAE y por ende lo tengo
que buscar a mano.

¿Alguno otro tuvo o tiene este problema?

Saludos

_Andres Misiak_

**Comment by jpmermoz** [comment]
@andresmaiden donde buscás el CAE a mano?
Gracias!

**Comment by andresmaiden** [comment]
Con el comando rece1.py /get
