### ISSUE TITLE
Error al imprimir

### ISSUE THREAD

**Issue by germanmr** [reingart/pyafipws#23]
Buenos días:

Estamos teniendo un error al imprimir.

El problema esta en las lineas de detalle.
Son dos lineas pero solo se ve una parte de la primera.

[FacturaA0003-00000032.pdf](https://github.com/reingart/pyafipws/files/163587/FacturaA0003-00000032.pdf)

El siguiente es el detalle del traceback:

{'code': "s = f.split_multicell(umed_ds, 'Item.Umed_ds01')
", 'name': 'IndexError', 'filename': './pyfepdf.py', 'lineno': 660,
'msg': 'IndexError: list index out of range\n',
'tb': 'Traceback (most recent call last):\n
File "./pyfepdf.py", line 660, in ProcesarPlantilla\n
s = f.split_multicell(umed_ds, \'Item.Umed_ds01\')\n
File "/usr/local/lib/python2.7/dist-packages/fpdf/template.py", line 100, in split_multicell\n....
if element[\'name\'].lower() == element_name.lower()][0]\nIndexError: list index out of range\n',.
'function_name': 'ProcesarPlantilla'}

suponemos que este Issue se da luego de la ultima actualización del pyfepdf.py

Muchas Gracias.

Saludos.

**Comment by reingart** [comment]
Tendrían que revisar el formato csv, por algun motivo parece no estar encontrando el campo Item.Umed_ds01 , 
¿uds borraron la columna de unidad de medida?
Si no usan esa columna, simplemente no envien el dato en el detalle (nulo/None, y en las últimas versiones, pueden pasarle string vacio)

**Comment by germanmr** [comment]
Muchas Gracias por la respuesta.

Efectivamente habiamos borrado la columna unidad de medida.

Recuperamos el factura.csv del repositorio y anduvo nuevamente.

Muchas Gracias.

Saludos.
