### ISSUE TITLE
Reimprimir comprobante recuperado

### ISSUE THREAD

**Issue by germanmr** [reingart/pyafipws#24]
Comportamiento no esperado al intentar generar PDF de comprobante recuperado de AFIP.

Consumimos

python ./rece1.py path archivo rece.ini /get tipocomprobante punto Venta numero Comprobante /json

Los archivos el archivo salida.json lo llena con los datos de la AFIP de manera correcta.

Consumimos:

python ./pyfepdf.py  path archivo rece.ini --cargar --json

El tema esta en que el JSON retornado es distinto a cuando se genera un comprobante por primera vez. Afip devuelve informacion en disintos formato en el XML.

Es esto lo que hace que el pyfepdf no genere el PDF?

Tendría que homologar el json al creado cuando se comsume el servicio de generar comprobante por primera vez?

Alcaración:
    La aplicación no loguea ningun tipo de error por ningun lado, pero el PDF NO es generado por el rece1.py

**Comment by reingart** [comment]
Por lo que veo, esto no es un error:
- los formatos de json son distintos entre pyfepdf.py y rece1.py
- rece1.py no genera PDF

En el manual pueden ver mas info:

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs

Se podría llegar a usar un formato comun entre ambas herramientas, ver por ej:

https://github.com/reingart/pyafipws/blob/master/ejemplos/factura_electronica.php

Para consultas y soporte comunitario, ver foro:

https://groups.google.com/forum/#!forum/pyafipws

**Comment by germanmr** [comment]
Dale, gracias por la respuesta. 
Sobre:
"rece1.py no genera PDF"
fue un error de tipeo, pyfepdf.py los genera.

No sabia del foro, voy a presentar ahí este tipo de temas y con mas detalle.

Muchas Gracias nuevamente.
