### ISSUE TITLE
Facturar cero pesos

### ISSUE THREAD

**Issue by lukio** [reingart/pyafipws#25]
Estoy tratando de generar una factura con valor cero pesos.
Al wsdl de la AFIP se le debe pasar iva_id = 3 (impuesto IVA 0%)
Del documento [manual_desarrollador_COMPG_v2.doc](http://www.afip.gov.ar/fe/documentos/manual_desarrollador_COMPG_v2.doc) leo que:

> Si <ImpIva> es igual a 0 los objetos <IVA> y <AlicIva> solo deben informarse con Id iva = 3 (iva 0)
> El tema es que el método AgregarIva se le pueden pasar los parámetros iva_id, base_imp e importe.

Lo que sucede es que el método AgregarIva siempre inicializa base_imp e importe en cero (0) y para este caso (iva_id == 3) esos datos no se requieren.

**Comment by reingart** [comment]
A `AgregarIva` se le puede pasar `None` en base_imp (en esos casos la etiqueta XML no se envía a AFIP -esto funcionaría para cualquier campo-).
Igualmente pude no ser necesario agregar una alicuota al 0% (habría que ver bien las validaciones de AFIP)
Lo cierro por el momento porque no sería un bug (creo).
