### ISSUE TITLE
unhashable type: 'dict'

### ISSUE THREAD

**Issue by cperezabo** [reingart/pyafipws#26]
Hola, estoy renegando con esto, estuve viendo un par de topicos iguales en los grupos de google, pero no encuentro solución.

El problema viene cuando se llama CAESolicitar()
Puse wsfev1.LanzarExcepciones en True para poder capturar los responses.

Esto es lo que obtuve.

*******************\* REQUEST ******************

```
<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soap:Header/>
<soap:Body>
    <FECompUltimoAutorizado xmlns="http://ar.gov.afip.dif.FEV1/">
    <Auth xmlns="http://ar.gov.afip.dif.FEV1/"><Token xmlns="http://ar.gov.afip.dif.FEV1/">PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8c3NvIHZlcnNpb249IjIuMCI+CiAgICA8aWQgdW5pcXVlX2lkPSIzOTQwMDE4NjcxIiBzcmM9IkNOPXdzYWFob21vLCBPPUFGSVAsIEM9QVIsIFNFUklBTE5VTUJFUj1DVUlUIDMzNjkzNDUwMjM5IiBnZW5fdGltZT0iMTQ1OTI3NTI1MyIgZXhwX3RpbWU9IjE0NTkzMTg1MTMiIGRzdD0iQ049d3NmZSwgTz1BRklQLCBDPUFSIi8+CiAgICA8b3BlcmF0aW9uIHZhbHVlPSJncmFudGVkIiB0eXBlPSJsb2dpbiI+CiAgICAgICAgPGxvZ2luIHVpZD0iQz1hciwgTz11YmVydGkgam9zZSBtYXJpYSwgU0VSSUFMTlVNQkVSPUNVSVQgMjAwODU2NTE5MzYsIENOPWZhY3R1cmFkb3IiIHNlcnZpY2U9IndzZmUiIHJlZ21ldGhvZD0iMjIiIGVudGl0eT0iMzM2OTM0NTAyMzkiIGF1dGhtZXRob2Q9ImNtcyI+CiAgICAgICAgICAgIDxyZWxhdGlvbnM+CiAgICAgICAgICAgICAgICA8cmVsYXRpb24gcmVsdHlwZT0iNCIga2V5PSIzMDYwMTA3OTkwNSIvPgogICAgICAgICAgICA8L3JlbGF0aW9ucz4KICAgICAgICA8L2xvZ2luPgogICAgPC9vcGVyYXRpb24+Cjwvc3NvPgoK</Token><Sign xmlns="http://ar.gov.afip.dif.FEV1/">qTjPANWmDbH5l7zQJ/lBYzOOpn81qPS9P5U1VQ9q1McAQEbO0WvZcJnPdb5auw3l3qoF4hYjvGw1sbUKL/1CRcK6tBysPuUbNybbEZBFWo/2MNqDXkvI8CmS4NgTCBhNpdKBAnGQQCwDwcuNzcL16g9pB7kncijVK9IyLGpFJC0=</Sign><Cuit xmlns="http://ar.gov.afip.dif.FEV1/">30601079905</Cuit></Auth><PtoVta>20</PtoVta><CbteTipo>6</CbteTipo></FECompUltimoAutorizado>
</soap:Body>
</soap:Envelope> 
```

*******************\* RESPONSE ******************

```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><FECompUltimoAutorizadoResponse xmlns="http://ar.gov.afip.dif.FEV1/"><FECompUltimoAutorizadoResult><PtoVta>20</PtoVta><CbteTipo>6</CbteTipo><CbteNro>0</CbteNro></FECompUltimoAutorizadoResult></FECompUltimoAutorizadoResponse></soap:Body></soap:Envelope>
```

Y tambien obtuve el siguiente trace originalmente.

```
Traceback (most recent call last):
  File "/Users/Cristian/IODuck/Clientes/Aprepa/FE/src/models.py", line 260, in run
    cae = wsfev1.CAESolicitar()
  File "/usr/local/lib/python2.7/site-packages/pyafipws/utils.py", line 150, in capturar_errores_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyafipws/wsfev1.py", line 229, in CAESolicitar
    }} for opcional in f['opcionales']] or None,
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 181, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 346, in wsdl_call
    return self.wsdl_call_with_args(method, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 367, in wsdl_call_with_args
    method, params = self.wsdl_call_get_params(method, input, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 399, in wsdl_call_get_params
    valid, errors, warnings = self.wsdl_validate_params(input, all_args)
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 469, in wsdl_validate_params
    next_valid, next_errors, next_warnings = self.wsdl_validate_params(struct[key], value[key])
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 469, in wsdl_validate_params
    next_valid, next_errors, next_warnings = self.wsdl_validate_params(struct[key], value[key])
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 469, in wsdl_validate_params
    next_valid, next_errors, next_warnings = self.wsdl_validate_params(struct[key], value[key])
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 487, in wsdl_validate_params
    next_valid, next_errors, next_warnings = self.wsdl_validate_params(struct_list_value, item)
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 469, in wsdl_validate_params
    next_valid, next_errors, next_warnings = self.wsdl_validate_params(struct[key], value[key])
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 469, in wsdl_validate_params
    next_valid, next_errors, next_warnings = self.wsdl_validate_params(struct[key], value[key])
  File "/usr/local/lib/python2.7/site-packages/pysimplesoap/client.py", line 465, in wsdl_validate_params
    if key not in struct:
TypeError: unhashable type: 'dict'
```

Aclaro que probé usar la versión que esta disponible en pypi (como se ve en el trace) para ambas librerias (pyafipws y pysimplesoap) y también la versión descargada desde github. Con todas pasa lo mismo.

Agradezco la ayuda desde ya.

**Comment by mggimenez** [comment]
Yo estoy teniendo el mismo problema. Probé combinaciones con distintas versiones desde GitHub y pypi de pyafipws y pysimplesoap con el mismo resultado:
- pyafipws: 93afbfbcd1f966134aa6c896bca19e2f95d54b85
- pyafipws: 9a812b6f60098066dda6accfff90b67a3db105e5
- pysimplesoap: HEAD
- pysimplesoap: 1.16
- pysimplesoap: 1.08.9

También estaré agradecido si podemos encontrar el origen del problema.

**Comment by cperezabo** [comment]
Mira, yo lo solucione, y de hecho no era un problema de la librería, sino mío.
Sin embargo, probe con una versión mas vieja que tenia y la forma en que mostró el error fue distinta. Eso me ayudo a encontrarlo mas fácilmente.
Basicamente tenia un valor incorrecto en el campo imp_iva.
Te diría en mi experiencia que pruebes lo siguiente:
1- borra la carpeta cache
2- hace un dumpeo del diccionario que estas pasándole a CrearFactura y revisa que los datos ingresados cumplan con los formatos esperados.
http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs

**Comment by mggimenez** [comment]
Finalmente pude solucionar el problema utilizando pysimplesoap-1.08.8, tal como dice en la documentación. Al hacer este cambio fue importante borrar la cache de pyafipws. No he tenido inconvenientes desde entonces.

Pido disculpas por el tiempo que ha pasado sin informar las novedades.

**Comment by dgaletto** [comment]
En mi caso lo solucione modificando el diccionario de CAESolicitar

Este:
`FeCAEReq={
                .........
                'FeDetReq': [{'FECAEDetRequest': {
                    'Concepto': f['concepto'],
                    'DocTipo': f['tipo_doc'],
                  ...... 
                }]
            })`

Por este:

`FeCAEReq={
                 .....
                'FeDetReq': {'FECAEDetRequest': {
                    'Concepto': f['concepto'],
                    'DocTipo': f['tipo_doc'],
                  ...... 
                }
            })`

Lo que hice fue sacar la lista de FeDetReq y dejar solo el dict, de esa forma dejo de dar el error y conecto sin problemas.

**Comment by reingart** [comment]
No es necesario realizar modificaciones, si utilizar la versión correcta de PySimpleSoap.

Recordar al instalar las dependencias, borrar la carpeta "cache" de archivos temporales para que se regeneren correctamente.

Ver documentación y requirements.txt:

https://github.com/reingart/pyafipws/wiki/InstalacionCodigoFuente
