### ISSUE TITLE
Instalar "sin instalador"

### ISSUE THREAD

**Issue by lcnvdl** [reingart/pyafipws#27]
Hola, quería usar la aplicación en AZURE, pero no puedo instalar cosas porque no me permiten acceder por remote desktop. Hay alguna forma de instalar las dll directamente dentro de una aplicación ? o desde línea de comandos ?

**Comment by reingart** [comment]
Podrías copiar la carpeta instalada en otra máquina, y ejecutar la registración (por ej. en un .bat o similar):

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#InstalaciónManualAvanzada

Para estas cuestiones ver de utilizar el foro público de soporte comunitario: http://groups.google.com/group/pyafipws (cierro el ticket porque no es una mejora ni bug)

Sds. M
