### ISSUE TITLE
Error al Validar factura AFIP o solicitar ultimo nro. de factura.

### ISSUE THREAD

**Issue by ljrodriguez** [reingart/pyafipws#29]
Buenos días.

Escribo para consultarles sobre un problema que estoy teniendo desde hace unos días y no puedo resolver. 
Estoy utilizando el modulo PyAFIPWs a través de ODOO. Realice un "pull" para tener la versión actualizada hoy 02/09/2016.
## El problema:

al momento de enviar los datos de una factura o pedir el ultimo nro. de factura a AFIP homologacion. me aparece el siguiente mensaje de error, pego dump:

> .... 
> File "/usr/local/lib/python2.7/dist-packages/pyafipws/utils.py", line 150, in capturar_errores_wrapper return func(self, _args, *_kwargs)
> 
> File "/usr/local/lib/python2.7/dist-packages/pyafipws/wsfev1.py", line 322, in CompUltimoAutorizado CbteTipo=tipo_cbte,
> 
> File "/usr/local/lib/python2.7/dist-packages/pyafipws/wsfev1.py", line 111, in __analizar_errores self.ErrCode = ' '.join([str(error['Err']['Code']) for error in errores])
> 
> ValueError: "code" while evaluating u'action_number()
- Consulte en los grupos y a otras personas les esta pasando lo mismo, y no lo han solucionado. 
- Existe alguna forma, para ver el XML que se arma y se envia a la AFIP y lo mismo con el response del XML que llega de AFIP ?
  Estimo que el programa esta intentando parsear un código sin éxito y genera el error.

Cualquier comentario, asi sea para encaminarme, me servirá. 

Desde ya muchas gracias !

Leonardo

**Comment by sindrunas** [comment]
El problema es que los genios de AFIP agregaron un warning en la respuesta de ese método que dice: "IMPORTANTE: El 01/11/2016 se renovarán los certificados SSL utilizados por los webservices de AFIP. Los nuevos certificados utilizarán el algoritmo de encriptación SHA-2. Para más información http://www.afip.gob.ar/ws/comoAfectaElCambio.asp <http://www.afip.gob.ar/ws/comoAfectaElCambio.asp> " y el método **analizar_errores** de PyAfipWS no lo atrapa bien.

**Comment by sindrunas** [comment]
El problema es que los de AFIP agregaron un warning en la respuesta de ese método que dice: "IMPORTANTE: El 01/11/2016 se renovarán los certificados SSL utilizados por los webservices de AFIP. Los nuevos certificados utilizarán el algoritmo de encriptación SHA-2. Para más información http://www.afip.gob.ar/ws/comoAfectaElCambio.asp http://www.afip.gob.ar/ws/comoAfectaElCambio.asp " y el método **analizar_errores** de PyAfipWS no lo atrapa bien.

**Comment by ljrodriguez** [comment]
Sindrunas, 

**Primero te agradezco mucho tu respuesta !**
Ok. Al enviar AFIP la respuesta con ese Warning, PyAFIPWs no podrá parsear el contenido por no el formato.
Entonces, hasta que no este contemplado el warning por el  PyAFIPWs cualquier función provista por WS AFIP (que no sea dummy o de status) pinchara. ¿ Entendí bien ?

Te consulto adicionalmente, quizás sepas: qué método o función recibe el XML ? así por lo menos hago un "print" y puedo ver lo que me llega de afip. _Como la invocación al PyAFIPWs la hace la plataforma de ODOO no conozco la librería de funciones._

Mucas Gracias !
Leonardo

**Comment by reingart** [comment]
Este tema está resuelto desde Abril en el repositoro, ver c072a0a2d337372ac0d61d5dd2830195ef7bb9f1 "WSFEv1: ajuste eventos (informativos)".

Lamentablemente es/era algo infrecuente (AFIP prácticamente no lo utilizaba regularmente, menos aún en producción) por lo que no pudo ser detectado antes.

Simplemente actualizando el archivo [wsfev1.py](https://github.com/reingart/pyafipws/blob/master/wsfev1.py) se debería solucionar (es recomendable actualizar todos los módulos y dependecias).

No es necesario realizar ninguna acción, pero para ver que XML se envía/recibe, ver atributos `WSFEv1.XmlRequest` y `WSFEv1.XmlResponse` del componente en la documentación (manual):

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#MensajesXML 

Para consultas de soporte comunitario, usar el foro público: https://groups.google.com/forum/#!forum/pyafipws

Cierro este ticket porque no es una cuestión activa en el código fuente, igualmente si es posible comentar el resultado de aplicar el ajuste para confirmar y cerrar definitivamente este tema.

**Comment by ljrodriguez** [comment]
Mariano, muchas gracias por tu rápida respuesta.
Felicitaciones por el desarrollo y el mantenimiento que le das a la librería.

Gracias por todo
Leonardo

**Comment by ljrodriguez** [comment]
Indícame si es necesario que cierre el tema yo mismo. Nunca utilice este gestor de versiones.

Gracias 
Leonardo

**Comment by cperezabo** [comment]
@ljrodriguez solo para aclarar.... este no es un "gestor de versiones".
GitHub es un servicio de alojamiento de repositorios Git, y Git es el sistema de control de versiones y acá donde estamos escribiendo (y donde vos queres cerrar tu tema) es el "sistema de seguimiento de temas" si se quiere...

**Comment by ljrodriguez** [comment]
Cristian, ok gracias por la aclaracion ... sigo aprendiendo.

Saludos

**Comment by vechettiariel** [comment]
Muchas Gracias por la respuesta y la ayuda para corregirlo. 

Saludos.
