### ISSUE TITLE
Compatibilidad OSX

### ISSUE THREAD

**Issue by fproldan** [reingart/pyafipws#36]
Hola, intentando utilizar pyafipws en OSX tengo un problema en la siguiente sección:
https://github.com/reingart/pyafipws/blob/master/wsaa.py#L115

Se podría modificar por algo como lo siguiente:
`if sys.platform in ["linux2", "darwin"]:`

Gracias!

**Comment by cperezabo** [comment]
Borra todo rastro de pythoncom, yo tengo un sistema funcionando en macOS con pyafipws
Cuando actualizo vuelvo a borrar, es básicamente alguna línea de import, y el main que no lo utilizas para nada, te lleva fracción de segundo hacerlo. Yo quería tirar un PR con algunas validaciones, pero no tuve tiempo para hacerlo en todos los archivos del proyecto asi que solo borre esas cosas del modulito que yo uso.
