### ISSUE TITLE
Error al Solicitar CAE

### ISSUE THREAD

**Issue by fproldan** [reingart/pyafipws#37]
Hola, estoy intentando obtener el CAE utilizando WSFEv1 (como referencia sigo el [codigo de Odoo](https://github.com/ingadhoc/odoo-argentina/blob/9.0/l10n_ar_afipws_fe/models/invoice.py ))
y obtengo el siguiente error de validacion:

```
Invalid Args Structure. Errors: [
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 10.00",
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 0.00",
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 0.00",
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 10.00",
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 1.00",
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 0.00",
u"Type mismatch. parameter(<class 'pysimplesoap.helpers.Alias'>): <alias 'double' for '<type 'float'>'>, value(<type 'str'>): 0.00"
]
```
Al crear la factura ya probe formateando los datos en distintos tipos, float, decimal, string, unicode y de ninguna forma logro superar este error.

La forma de formatear los datos que utilizan en Odoo y Tryton es la siguiente:
`imp_total = str("%.2f" % abs(doc.grand_total))`

¿Alguna idea de donde puede estar el problema?

Muchas gracias

**Comment by reingart** [comment]
Este es un tema de instalación, revisar `requirements.txt` (dependencia `pysimplesoap==1.08.8`)

Se podría adaptar para convertir los tipos al validado, pero esto puede ocasionar errores de redondeo en ciertas ocasiones (por ej. dependiendo del lenguaje de programación / base de datos con la que se trabaje). También se podría deshabilitar o adaptar la validación.
Se aceptarían PR (mejoras), pero habría que hacerlo en un branch distinto hasta que esté estabilizado.

Ver [foro público](https://groups.google.com/d/msg/pyafipws/vic88NrUy5o/mdU12MN2CQAJ) para más información.
