### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED - Corrección de comparación de versiones en utils.py

### ISSUE THREAD

**Issue by evetere** [reingart/pyafipws#48]
Hice un pull request para corregir la comparación de versiones (que estaba hecha en base a strings) en utils.py.
Estoy usando httplib2 version 0.11.3 y la comparación existente, al ser strings, falla con 0.3.0 y también con 0.7.0, por lo tanto no setea correctamente los kwargs.
Llegué a eso traceando el problema de SSL: CERTIFICATE_VERIFY_FAILED al usar iibb.py desde odoo 8.
Esta corrección solucionó el problema para mi.
https://github.com/reingart/pyafipws/pull/47

**Comment by reingart** [comment]
Muchas Gracias! merged in cb6a64a
