### ISSUE TITLE
Se pierde el registro de los componentes

### ISSUE THREAD

**Issue by hdeantoni** [reingart/pyafipws#7]
Descargué la última versión release de prueba desde GitHub cuyo archivo se llama "PyAfipWs-2.7.1511-32bit.wsaa_2.08a.wsfev1_1.15c.wsfexv1_1.08b.wsbfev1_1.06b.wsmtx_1.12a.wscdc_1.02b-homo.exe" lo ejecuto y se registran correctamente los componentes, por ejemplo wsaa. Pero cuando reinicio la PC y vuelvo a ingresar los componentes se desregistran y para que vuelva a funcionar tengo que volver a instalarlo.
Probé con versiones anteriores del instalador y sucede lo mismo. También probé generar yo mismo el instalador y ocurre lo mismo.
Tengo sistema operativo Window 7.

**Comment by reingart** [comment]
No entiendo bien, ¿no tendrás algún sistema de congelamiento de la máquina (deep freeze o algo similar)?
Sinceramente se ha probado en varias máquinas y es la primera vez que escucho este tipo de problema.
¿Lo están instalando como administradores?

Workaround: Por el momento pueden probar instalarlo de manera autonoma:

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#InstalaciónManualAvanzada

Ver:

https://groups.google.com/d/msg/pyafipws/OVQ2s6U1iz0/ObYbGZbZ51kJ

También pueden probar los instaladores más recientes subidos a nuestro sitio:

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#Descargas

**Comment by hdeantoni** [comment]
Probé en otras PCs con Windows Seven, lo instalé de la misma manera y funcionó perfectamente. Con seguridad es un problema en la configuración de mi PC, sospecho que puede estar relacionado con los permisos.
Muchas gracias por tu disposición y pronta respuesta.
