### ISSUE TITLE
WSFEX: actualizacion a version 1.6 23/09/2019 | Nuevo campo Fecha_pago

### ISSUE THREAD

**Issue by lukio** [reingart/pyafipws#72]
Cambios aplicados en versión *1.6* del manual del desarrollador para WSFEX.
https://www.afip.gob.ar/ws/documentacion/manuales/WSFEX-Manualparaeldesarrollador_V1_6_0.pdf

> Se modifica la validación 1668. Cuando el tipo de exportación
es 4 (Tipo_expo=4) no se valida que se encuentre registrado
como exportador.
Se agrega fecha de pago en autorización y consulta de
comprobantes que son del tipo Factura de Servicios u Otros.
Validaciones 1671, 1672, 1673, 1674. Para dar soporte al
requerimiento se modifican los complexType ClsFEXRequest
y ClsFEXGetCMPR. La fecha de pago debe informarse, a
partir del 01/11/2019 será obligatorio.
Se agrega el siguiente código de validación 2055

Validaciones:

- 2055: Para comprobante de Servicio (Tipo_expo=2), la Nota de Debito asociada que informa debe tener una FACTURA (Cbte_tipo=19) de servicio (Tipo_expo=2) asociada.
- 1671: Si informa fecha de pago <Cmp><Fecha_pago> debe tener formato válido YYYYMMDD.
- 1672: Para comprobantes del tipo “19 - Facturas de Exportación” donde el tipo de exportación es “2 – Servicios / 4 - Otros” la fecha de pago <Cmp><Fecha_pago> es obligatoria.
- 1673: Para comprobantes que no son tipo “19 - Facturas de Exportación” la fecha de pago <Cmp><Fecha_pago> no debe informarse.
- 1674: Para comprobantes del tipo “19 - Facturas de Exportación” donde el tipo de exportación es “2 – Servicios / 4 - Otros”, la fecha de pago debe ser igual o posterior a la fecha de emisión del comprobante.

**Comment by jvi-mastercore** [comment]
Buen día, estoy probando los cambios (Python 3) y me da el siguiente mensaje de error de la afip:      

>      <ErrCode>1672</ErrCode>
>           <ErrMsg>Para facturas de exportacion (2 – Servicios / 4 - Otros) es obligatorio informar la fecha de pago</ErrMsg>

Comprobé en el método CrearFactura que me estuviera llegando el valor correcto en fecha_pago y está todo correcto.


Algún indicio de lo que podría estar pasando?

Gracias por los aportes.

**Comment by fabioariel** [comment]
> 
> 
> Buen día, estoy probando los cambios (Python 3) y me da el siguiente mensaje de error de la afip:
> 
> > ```
> >  <ErrCode>1672</ErrCode>
> >       <ErrMsg>Para facturas de exportacion (2 – Servicios / 4 - Otros) es obligatorio informar la fecha de pago</ErrMsg>
> > ```
> 
> Comprobé en el método CrearFactura que me estuviera llegando el valor correcto en fecha_pago y está todo correcto.
> 
> Algún indicio de lo que podría estar pasando?
> 
> Gracias por los aportes.



> 
> 
> Buen día, estoy probando los cambios (Python 3) y me da el siguiente mensaje de error de la afip:
> 
> > ```
> >  <ErrCode>1672</ErrCode>
> >       <ErrMsg>Para facturas de exportacion (2 – Servicios / 4 - Otros) es obligatorio informar la fecha de pago</ErrMsg>
> > ```
> 
> Comprobé en el método CrearFactura que me estuviera llegando el valor correcto en fecha_pago y está todo correcto.
> 
> Algún indicio de lo que podría estar pasando?
> 
> Gracias por los aportes.

jvi-mastercore: tengo el mismo problema. Lo solucionaste? si es así y podés tirá idea....

**Comment by guillermoeuillades** [comment]
> Buen día, estoy probando los cambios (Python 3) y me da el siguiente mensaje de error de la afip:
> 
> > ```
> >  <ErrCode>1672</ErrCode>
> >       <ErrMsg>Para facturas de exportacion (2 – Servicios / 4 - Otros) es obligatorio informar la fecha de pago</ErrMsg>
> > ```
> 
> Comprobé en el método CrearFactura que me estuviera llegando el valor correcto en fecha_pago y está todo correcto.
> 
> Algún indicio de lo que podría estar pasando?
> 
> Gracias por los aportes.

Tuve este error también, el problema estaba en la carpeta de cache de pyafipws en mi caso ubicada en /usr/local/lib/python3.5/dist-packages/pyafipws/cache. Eliminar todos los archivos que hay en esa carpeta  y listo.

**Comment by lukio** [comment]
Cierro el ticket ya que el error reportado por https://github.com/reingart/pyafipws/issues/72#issuecomment-550482395 tiene que ver con actualizar la cache del wsdl.

**Comment by Ren14** [comment]
Hola ! 

Yo estuve teniendo el mismo problema utilizando python 2.7 en Ubuntu 16. Lo solucioné modificando el archivo recex1.py en la línea 77 (donde está la definición del formato del archivo de intercambio), precisamente cambié fecha_vto por fecha_pago. 

Saludos.

**Comment by vsa-ok** [comment]
Hola, estuve viendo la integración en este punto. Noté que si se quiere hace una nota de crédito Exportación de Servicios, tira error de validación N°1673. Esto es que no hay que informar fecha de pago en tipos de comprobantes distintos a 19. No sé si ya lo habían visto, pero lo solucioné agregando un if dentro del método "CrearFactura" poniendo a None el parámetro fecha_pago. Lo pongo acá porque mi sistema no verificaba esa validación.

**Comment by vsa-ok** [comment]
Hola, @lukio , estuve viendo la integración en este punto. Noté que si se quiere hace una nota de crédito de Exportación de Servicios tira error de validación N°1673. Esto es que no hay que informar fecha de pago en tipos de comprobantes distintos a 19. No sé si ya lo habían visto, pero lo solucioné agregando un if dentro del método "CrearFactura" poniendo a None el parámetro fecha_pago. Lo pongo acá porque mi sistema no verificaba esa validación.

Saludos.
