### ISSUE TITLE
pyemail envio correo

### ISSUE THREAD

**Issue by oscarvogel** [reingart/pyafipws#75]
Al intentar enviar un correo da un error de que el componente no tiene una propiedad llamada MensajeTexto, esto se debe a esta linea

`self.MensajeHTML = MensajeTexto = None`

en realidad deberia ir 

`self.MensajeHTML = self.MensajeTexto = None`

**Comment by reingart** [comment]
Gracias @oscarvogel ! ahi esta corregido en develop
