### ISSUE TITLE
SoapClient: ExpatError: mismatched tag: line 1, column 50

### ISSUE THREAD

**Issue by dRowie** [reingart/pyafipws#79]
Hola,

muy bueno el paquete pysiemplesoap.

quería consultarte si podías ayudarme con un problema del PySimpleSoap.

Cuando intento conectar al:

```
client = SoapClient(wsdl="https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL")`
```
Con la intención de pasar el método (no llego a hacerlo porque la primera línea me tira error):

```
result = client.getPersona_v2(token=ta_token, sign=ta_sign, cuitRepresentada=20123456789, idPersona=20123456789)`
```

Me muestra este error:

```
Message: b'<html><head><title></title></head><body><br><br></body></html>'
Arguments: ()
ExpatError: mismatched tag: line 1, column 50
```

Ya vi este post (https://github.com/reingart/pyafipws/issues/43) que explica que el problema se debe a " Posiblemente sea un problema de URL, el ExpatError es que no puede interpretar el XML devuelto por el servidor."

Como no estoy usando la clase padron, sino directamente el SoapClient (me funcionó esta manera para generar el TA), entiendo que no debería interpretar el xml sino devolverlo sea cual sea. O tal vez me equivoco. Toco de oído todo este tema. Quería saber si podías orientarme por dónde solucionar el problema. 

Desde ya agradezco cualquier ayuda que puedas darme.

Saludos

**Comment by reingart** [comment]
Ese error es porque el servidor no esta devolviendo un XML
Capaz justo AFIP estaba actualizando el servidor.

Otra opción es que tengas en cache un WSDL viejo (borrar archivos temporales en el directorio cache)

Te recomiendo revisar el componente y la clase en utils, donde a veces se corrige el location (URL) que AFIP en algunos ws no publica correctamente:

 * https://github.com/reingart/pyafipws/blob/master/ws_sr_padron.py
 * https://github.com/reingart/pyafipws/blob/master/utils.py#L282

Tenemos una lista de correo para consultas técnicas:

https://groups.google.com/forum/#!forum/pyafipws
