### ISSUE TITLE
unsupported operand type(s)

### ISSUE THREAD

**Issue by DanielCernotto** [reingart/pyafipws#8]
En el ejemplo  Uso de Interface COM para generar Facturas Electrónica en formato PDF  si lo ejecuto directamente al ejemplo, trabaja ok.

Si lo incluyo en una Function en mi proyecto, me pide definir las variables. 
Luego al ejecutarlo, se produce un error al invocar PyFEPDF.GenerarPDF(Salida)

El error es:

Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 189, in capturar_errores_wrapper
  File "pyfepdf.pyc", line 789, in GenerarPDF
  File "fpdf\template.pyc", line 128, in render
  File "fpdf\template.pyc", line 163, in text
TypeError: unsupported operand type(s) for -: 'unicode' and 'int'

Alguna idea para solucionarlo?

Gracias

**Comment by reingart** [comment]
Para consultas por favor usar el foro público de soporte comunitario:

http://groups.google.com/group/pyafipws

(estos tickets no los reviso frecuentemente, y generalmente tampoco lo ven otros desarrolladores/usuarios)

Lo respondo igualmente por si alguien tiene un problema similar:  

Habria que revisar la función, como se definieron las variables (en el futuro adjuntar el fragmento de código para poder reproducirlo).
Generalmente es un problema de tipos de datos incorrectos en el tipo de comprobante, punto de venta, numero de comprobante o similar. Lo recomendado es pasar los valores como string:

http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#Erroresdetiposdedatos
