### ISSUE TITLE
Error el al compilarf para windows

### ISSUE THREAD

**Issue by fjbardelli** [reingart/pyafipws#93]
Hola estoy teniendo un error al compilar para windows, lo probe con python 2.7 y 3.9 32 y 64 bits

Gracias

C:\pyafipws>python setup.py py2exe
C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py:501: UserWarning: The version specified ("3.9.b'2731'") is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'py2exe'

**Comment by reingart** [comment]
La rama main todavía no tiene soporte para generar instaladores con py2exe (por algunas cuestiones de python3 que hay que ajustar)

Lo tenemos pendiente, si te interesa puedo ver de subir algunas pruebas preliminares que debería tener por algún lado si mal no recuerdo.

De hecho, buscamos nuevos colaboradores, es una de las ideas que propusimos para las becas GSoC 2022:  https://wiki.python.org.ar/GSoC/2022/#pyafipws (este año esta abierta la participación a nuevos desarrolladores +18 años)

Por ahora para generar el .exe deberías usar la rama develop (python2 .7), si te surge algún inconvenientes podes subir por aca el problema y lo vemos.

**Comment by fjbardelli** [comment]
Dale gracias voy a usar esa rama, y voy a ver que posibilidades me da el tiempo para colaborar,

**Comment by fjbardelli** [comment]
Con la rama develop me de el mismo error 

Z:\vb6\ws\pyafipws>git branch
* develop
  main

Z:\vb6\ws\pyafipws>python setup.py py2exe
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'py2exe'

Z:\vb6\ws\pyafipws>

**Comment by reingart** [comment]
¿Podrías adjuntar la salida de `pip freeze`?
Quizás es un tema de instalación de dependencias.
Tambíen puede que tengas algún problema al descargar los archivos, te recomiendo comparar el archivo de setup con el de la rama https://github.com/reingart/pyafipws/blob/develop/setup.py (debería tener el código para py2exe)

**Comment by fjbardelli** [comment]
Gracias había un problema al clonar la rama, ya pude hacerlo, lo pruebo gracias.
