### ISSUE TITLE
muchos problemas para primer uso

### ISSUE THREAD

**Issue by acognigni-evotecnia** [reingart/pyafipws#96]
Buenos dias. es la primera ves qie estoy intentando usar esta libreria y me estoy chocando contra un monton de paredes

lo estoy haciendo correr en una vm  con ubuntu 22.04.1 LTS. (tambien lo intente en windows y me encontre con practicamentelos mismos problemas)

Errores de codigo y entorno:
-  `sudo apt-get install python-httplib2 python-m2crypto` no funciona. lo tuve que cambiar a `sudo apt-get install python3-httplib2 python3-m2crypto`
- si intento instalar los requisitos con pip python 2 da error de m2crypto
- si lo ejecuto con pip python 3 funciona
- si intento ejecutar wsaa con python 3 me da `SyntaxError: multiple exception types must be parenthesized`. este error me inidca que el codigo no es compatible con python 3 ya que intenta hacer `except Exception, e:` que no esta permitido en esta version
- si intento ejectuarlo con python 2 me da `Excepcion: RuntimeError: Imposible abrir reingart.crt`, que parece indicar que esta funcionando excepto porque no encuentra el certificado
- no se puede descargar el certificado como lo indica la documentacion (error 404)

errores de documentacion:
- la documentacion esta extremandamente enredada, llena de nlaces autoreferenciados, y errores 404
- no se entiende la diferencia entre PyAfipWS y LibPyAfipWS. suena a que hacen y son lo mismo
- esos dos proyectos aparentan ser binarios compilados / dll, pero no exiten enlaces de descargar o dan 404
- no hay instrucciones de como compilar PyAfipWS y LibPyAfipWS. como binario / dll

Esos son solo algunos problemas de los que me encontre. llevo como dos dias intentando poder empezar a usar la libreria.
lo que mande aca, es el resultado de crear snapshots de ubuntu, probar, si falla restaurar la snapshot y volver a probar hasta entender mas los errores

**Comment by acognigni-evotecnia** [comment]
me falto agregar que si bien se que esta la documentacion de como hacer la instalaicon de la libreria (sin entender como compilar), la documentacion esta tan enredada que no se donde estabala parte que explicaba eso

**Comment by reingart** [comment]
Hola @acognigni-evotecnia , gracias por el feedback.

¿Que branch estas utilizando?
Deberías probar la rama principal (main) y en python 3, es la más indicada para soporte comunitario.
Con `pip install -r requirements.txt` debería funcionar.
El error de certificado es porque debes tramitarlos ante AFIP para poder utilizer los webservices, eso indica igualmente que estaría todo correctamente instalado.
Podes descargar nuestro certificado de pruebas [reingart2021.zip](https://www.sistemasagiles.com.ar/soft/pyafipws/reingart2021.zip), y deberías configurar el `rece.ini` (copiar del directorio conf)

La rama python 2 es solo para clientes legados y sistemas operativos mas antiguos, no es indicado para nuevos desarrollos ni soporte comunitario..
m2crypto no es más necesario, se reemplazó por el paquete cryptography.
Proximamente seguramente realice una limpieza y deje solo el código para Python3 asi evitamos confusiones.

LibPyafipWS es justamente un "envoltorio" para los los módulos python (en el directorio `src` están los fuentes).
Es más que nada para usuarios avanzados de C, y también ha quedado como ejemplo pero hoy por hoy es más simple utlilizar las herramientas por línea de comandos (`rece1.py``) y archivos de intercambio JSON que pueden utilizarse desde cualquier lenguaje.

No entiendo la última parte, si es la compilación para windows podes ver la [WIKI](https://github.com/reingart/pyafipws/wiki/InstalacionCodigoFuente#windows).
También se puede utilizar en windows sin instalar, simplemente se registran los componentes con `--register` (esta indicado en esa página)
Tengo pendiente actualizar el paquete en PYPI para poder instalar con `pip install` , por ahora se puede instalar con `python setup.py install` en cualquier entorno Python (Linux, Windows o Mac)

Veo que el README quedó con algunas cosas sin actualizar, en cuanto pueda lo reviso.
Igualmente si podes enviarnos las cuestiones puntuales, páginas y links que están incorrectos es más simple para poder revisarlos e indicarte si hay alternativas.

Cualquier duda avisanos, sds, M

**Comment by acognigni-evotecnia** [comment]
- las instrucciones que yo segui son las que estaban en el readme de el main y la unica documentacion de la que estaba al tanto son las paginas web que son los primeros dos resultados en google (https://www.pyafipws.com.ar/ y http://www.sistemasagiles.com.ar). esos son los sitios que me resultron poco utiles combinado con el hecho de que el readme del main esta desactualziado y no referencia a la wiki de github (la pagina web tampoco apunta a la wiki de github)
- las dependencias indicadas dicen ser para python 2.7 mientras que me mencionaste que el sistema usa python 3 ( de hecho tiene el enlace de descarga de python 2.7 y dice que todavia no tiene python3)
- el enalce de descarga de win64openssl da 404
- el enlace de descarga de m2crypto lleva a la pagina de un organizador de notas
- el enlace de descarga de httplib2 da 404
- las descargars de pywin32 se movieron a guithub (https://github.com/mhammond/pywin32/releases/latest)
- pil / pillow no detecta python 3 (se instala igual)
- py2exe no detecta python 3 y no se instala (voy a proseguir con depurar eso)

**Comment by acognigni-evotecnia** [comment]
py2exe seguramente no se instalaba porque es una version vieja, segun la web la nueva se instala desde pip directamente pero no se me esta registrando como comando asi que me da error: invalid command 'py2exe'

**Comment by reingart** [comment]
El readme esta desactualizado pero no tiene información incorrecta.
De hecho funciona tanto para python 2 y python 3 y las dependencias varian entre las distintas plataformas (el requirements.txt cubre ambas)
Tambien esta indicado al final _"For more information see the source code installation steps in the [wiki](https://github.com/reingart/pyafipws/wiki/InstalacionCodigoFuente)"_

En las otras páginas pyafipws.com.ar y www.sistemasagiles.com.ar también hay enlaces a la wiki, algunos apuntan al sitio antiguo de Google Code que fue archivado y reemplazado en github.

Lamento que no haya sido visible, vamos a tratar de revisar todos los links mencionados y mejorar la documentación.
Han pasado +14 años desde el inicio del proyecto, y si, nos han quedado muchas cosas acumuladas.
El cambio de Python3 afecta bastante porque no había mucho soporte para windows (y sinceramente por ello seguimos con python 2 lo máximo posible).

En el [foro público](https://groups.google.com/g/pyafipws) los usuarios van reportando versiones actualizadas de las dependencias (es difícil mantener algunos como OpenSSL que van publicando nuevos releases periódicamente)

Efectivamente están listadas las dependencias para python 2.7 porque se instalaban manualmente. 
Ahora en python 3 no sería necesario, pero todavía hay algunas que son opcionales y/o están comentadas (como pywin32).
Me lo llevo para ver de dejarlo en el requirement.txt más explicito o hacer otro especifico para Windows.

Lo de py2exe en el momento que migramos a Python3 todavía no estaba soportado.

Igualmente, como solución temporal, no sería necesario generar el instalador para usarlo.
Se podría registrar los componentes y utilizarlos con:
```
python setup.py install
python -m pyafipws.wsaa --register
python -m pyafipws.wsfev1 --register
```

Diría de crear otro ticket para py2exe, evidentemente hay un problema con las ultimas versiones.
Cree un branch py2exe para seguir el tema: https://github.com/reingart/pyafipws/tree/py2exe
Para probarlo habría que ejecutar el `setup_win.py`:
````
python setup_win.py py2exe
`````
Esta lanzando un `AssertionError` en python porque no encuentra un modulo en pyhon 3.9
Con una versión anterior de `py2exe==0.11.0.1` también encuentra un SyntaxError

Tengo pendiente hacer un GitHub Actions (Integración continua) para probar estas cosas automáticamente en windows.
Actualmente solo esta cubierto linux, voy a tratar de implementarlo este fin de semana.

Desde ya toda colaboración es bienvenida

**Comment by acognigni-evotecnia** [comment]
Como se habra notado cuando cree el ticket queria usar este proyecto por su larga trayectoria  pero estaba frutrado con estos problemas. sin embargo las respuestas rapidas y completas me han cambiado la opinion y ahora estoy mucho mas optimista para el uso. 
Me preocupaba que la documentacion este mal a proposito para hacerme pagar soporte pero aahora veo que no.

Muchas gracias

**Comment by acognigni-evotecnia** [comment]
pareciera faltar la dependencia pywin32

antes de instalarla me daba `ImportError: No module named pythoncom`

**Comment by reingart** [comment]
Gracias de nuevo por el feedback y las pruebas.

Si, los paquetes para Windows son opcionales, y las versiones antiguas pueden no encontrarse, por lo que se complica dejarlo en el requirement.txt (por eso estaba comentado).

Podes ver el [Pull Request #97](https://github.com/reingart/pyafipws/pull/97) donde estoy actualizando y moviéndolo al requirements_dev.txt
Estuve solucionando algunos temas con las ultimas versiones de py2exe para Python3. 
Ya se están compilando los ejecutables automaticamente, pero todavía no pude probarlo bien.
Igualmente en [Releases](https://github.com/reingart/pyafipws/releases) se se a poder descargar la version de desarrollo (zip con los .exe), y en las [Actions](https://github.com/reingart/pyafipws/actions) seguir el avance del proceso automatizado.

Si el problema persiste, provisoriamente es posible usar el branch [develop](https://github.com/reingart/pyafipws/tree/develop) que continua con Python2.7 y no deberia haber inconvenientes en generar el instalador para windows.

En el foro hay un mensaje detallado con los pasos reportados por otros usuarios, ver tema [wsaa.py:33: UserWarning: No es posible importar M2Crypto (OpenSSL)](https://groups.google.com/g/pyafipws/c/QyXH79EFk2E/m/cDWUm5dcAAAJ)

Cualquier duda avisanos

**Comment by acognigni-evotecnia** [comment]
Vuelvo a abrir esto porque llevo 4 horas intentando instalar todo en un servidor nuevo (windows).

- No es para nada claro que branch o zip hay que usar ( main? o master? No deberian existir esas dos ramas ya que las dos se llaman como branch principal y es confuso para todos.)
- la documentacion se contradice. 
- que version de python hay que usar?
- no estan todos los requisitos en requirenments.txt
- la docuemntacion aveces ejecuta python con ruta abosluta, lo cual es una buena idea, pero despues setup.bat usa el de variables de entorno.
- no queda claro si tengoo que ejecutar el setup.py, setup.bat o setup_win.bat
- las intrucciones para generar instalador con win2py no funcionan
- - muchas cosas mas

**Comment by acognigni-evotecnia** [comment]
en este caso logre instalr todo despues de buscar fragmentos de codigos a travez de todas las documentaciones y darme cuenta que estaba usando python 3.11 que no es compatible con pyafipws

**Comment by reingart** [comment]
FYI ya está actualizado el [README](https://github.com/reingart/pyafipws/blob/main/README.md).

Además ya están los workflows de GitHub Actions para compilar los ejecutables para windows, ver [windows-installer.yml](https://github.com/reingart/pyafipws/blob/main/.github/workflows/windows-installer.yml) con los pasos detallados y automatizados.
Se pueden descargar los ejecutables compilados automáticamente desde: https://github.com/reingart/pyafipws/releases 

No lo he probado en Python 3.11 (si es posible necesitaríamos el mensaje de error o detalle de dificultades para poder revisarlas).
Igualmente como está el otro ticket cierro este.

Gracias por los comentarios, desde ya pueden probarlo y toda colaboración/sugerencia es bienvenida
