### ISSUE TITLE
Como saber cuando hay una nueva version?

### ISSUE THREAD

**Issue by acognigni-evotecnia** [reingart/pyafipws#98]
En la mayoria de los repositorios puedo pedirle a github que me mande notificacioens cuando se hace un release pero el ultimo release de este repositorio es del 2016.

¿Existe alguna mailing list o algo similar? ¿Como puedo hacer?

**Comment by ZombieEater** [comment]
> En la mayoria de los repositorios puedo pedirle a github que me mande notificacioens cuando se hace un release pero el ultimo release de este repositorio es del 2016.
> 
> ¿Existe alguna mailing list o algo similar? ¿Como puedo hacer?

https://groups.google.com/g/pyafipws   Este grupo tiene bastante movimiento.

**Comment by acognigni-evotecnia** [comment]
Bueno. No es mi opcion favorita ya que voy a terminar recibien muchos mails que no me importan

Voy a esperar a ver si alguien mas me da otra opcion, de lo contrario lo considero cerrado

**Comment by ZombieEater** [comment]
El digesto que te manda un resumen diario está bueno, yo uso esa modalidad.

**Comment by reingart** [comment]
Hola @acognigni-evotecnia ! 
Estoy terminando de ajustar el tema de release automático en el PR #97 

Pueden ver uno preeliminar en:
https://github.com/reingart/pyafipws/releases/tag/beta

Seguramente se publique con el tag `latest` y se podrá usar el tema de notificaciones.
Se usa "rolling release" (liberación continua), por lo que cada conjunto de cambios mergeados a la rama principal sería una versión...

Tengo pendiente el tema de automatizar la publicación en [PyPI](https://pypi.org/project/PyAfipWs/) (índice de paquetes de python), seguramente lo haga ASAP en otro PR.

Igualmente como comenta @ZombieEater las novedades importantes se comentan por el foro, puede que no haya un release especifico para algunos cambios de AFIP.
Ej. protocolos de seguridad, cambios en validaciones de negocio o nuevos campos opcionales por las RG en general no requieren cambios en el código del proyecto (salvo que tengan una versión muy desactualizada)
Nuevos webservices y modalidades si requieren actualización, pero son cuestiones más puntuales (que igualmente vamos comentando en el foro)

**Comment by acognigni-evotecnia** [comment]
Perfecto!
